;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @sfx_ntsc_0, @sfx_pal_0
	.word @sfx_ntsc_1, @sfx_pal_1
	.word @sfx_ntsc_2, @sfx_pal_2
	.word @sfx_ntsc_3, @sfx_pal_3

	
@sfx_ntsc_0:
	.byte $80,$3f,$81,$56,$82,$03,$06,$81,$ab,$82,$01,$06,$81,$d5,$82,$00
	.byte $06,$00
@sfx_pal_0:
	.byte $80,$3f,$81,$19,$82,$03,$05,$81,$8c,$82,$01,$05,$81,$c6,$82,$00
	.byte $05,$00
@sfx_ntsc_1:
	.byte $80,$3f,$81,$ff,$82,$07,$89,$3f,$8a,$0f,$18,$00
@sfx_pal_1:
	.byte $80,$3f,$81,$ff,$82,$07,$89,$3f,$8a,$0f,$14,$00
@sfx_ntsc_2:
	.byte $80,$3f,$81,$d5,$82,$00,$06,$80,$30,$06,$80,$3f,$06,$00
@sfx_pal_2:
	.byte $80,$3f,$81,$c6,$82,$00,$05,$80,$30,$05,$80,$3f,$05,$00
@sfx_ntsc_3:
	.byte $80,$3f,$81,$ce,$82,$02,$06,$81,$67,$82,$01,$06,$81,$ce,$82,$02
	.byte $06,$81,$67,$82,$01,$18,$00
@sfx_pal_3:
	.byte $80,$3f,$81,$9b,$82,$02,$05,$81,$4d,$82,$01,$05,$81,$9b,$82,$02
	.byte $05,$81,$4d,$82,$01,$14,$00
